// Official question lists from CSP and CR exams
// Used to generate complete questions with options and explanations

export const cspQuestions = [
  // Principes et valeurs de la République (37 questions)
  { q: "À quoi correspond la date du 14 juillet ?", cat: "Principes et valeurs" },
  { q: "Quel est l'un des symboles de la République française ?", cat: "Principes et valeurs" },
  { q: "Le principe d'égalité signifie que :", cat: "Principes et valeurs" },
  { q: "\"Liberté, égalité, fraternité\", c'est :", cat: "Principes et valeurs" },
  { q: "A-t-on le droit d'insulter publiquement quelqu'un parce qu'il est différent (handicap, apparence physique, sexe…) ?", cat: "Principes et valeurs" },
  { q: "Certains métiers peuvent-ils être réservés aux hommes ?", cat: "Principes et valeurs" },
  { q: "De quand date la Constitution de la Ve République ?", cat: "Principes et valeurs" },
  { q: "Le régime de la France est :", cat: "Principes et valeurs" },
  { q: "Lequel de ces symboles représente officiellement la République française ?", cat: "Principes et valeurs" },
  { q: "Où peut-on voir la devise de la République ?", cat: "Principes et valeurs" },
  { q: "Quels sont des symboles officiels de la République française ?", cat: "Principes et valeurs" },
  { q: "Qu'est-ce que l'égalité ?", cat: "Principes et valeurs" },
  { q: "Que signifie la liberté ?", cat: "Principes et valeurs" },
  { q: "Que signifie le mot \"fraternité\" dans la devise française ?", cat: "Principes et valeurs" },
  { q: "Quel animal est un symbole de la France ?", cat: "Principes et valeurs" },
  { q: "Quel est l'un des rôles des associations ?", cat: "Principes et valeurs" },
  { q: "Quel est le nom de l'hymne national ?", cat: "Principes et valeurs" },
  { q: "Quel symbole de la République française est tricolore ?", cat: "Principes et valeurs" },
  { q: "Quelle est la date de la fête nationale française ?", cat: "Principes et valeurs" },
  { q: "Quelle est la devise de la République française ?", cat: "Principes et valeurs" },
  { q: "Quelle est la langue officielle de la République française ?", cat: "Principes et valeurs" },
  { q: "Quelle est la place de la langue française dans la République ?", cat: "Principes et valeurs" },
  { q: "Quelle liberté permet à chacun d'exprimer ses idées ?", cat: "Principes et valeurs" },
  { q: "Quelle proposition est correcte ? La liberté d'expression :", cat: "Principes et valeurs" },
  { q: "Quelles sont les couleurs du drapeau français ?", cat: "Principes et valeurs" },
  { q: "Qu'est-ce que la Marseillaise ?", cat: "Principes et valeurs" },
  { q: "Qu'est ce qui est traditionnellement organisé sur les Champs Élysées le 14 juillet pour célébrer la fête nationale ?", cat: "Principes et valeurs" },
  { q: "Qui est Marianne ?", cat: "Principes et valeurs" },
  { q: "Une personne peut-elle changer librement de religion ?", cat: "Principes et valeurs" },
  { q: "\"La France est une République indivisible, ..., démocratique et sociale\". Complétez cette phrase extraite de l'article 1er de la Constitution :", cat: "Principes et valeurs" },
  { q: "En quelle année la loi de séparation des Églises et de l'État a-t-elle été votée ?", cat: "Principes et valeurs" },
  { q: "Que permet le principe de laïcité ?", cat: "Principes et valeurs" },
  { q: "Quel droit est garanti par la laïcité ?", cat: "Principes et valeurs" },
  { q: "Pourquoi le principe de laïcité doit-il être respecté à l'école ?", cat: "Principes et valeurs" },
  { q: "Qu'est-ce que la laïcité ?", cat: "Principes et valeurs" },
  { q: "Un enfant peut-il refuser d'aller à l'école pour une raison religieuse ?", cat: "Principes et valeurs" },
  { q: "Une personne a-t-elle le droit de ne pas croire en une religion ?", cat: "Principes et valeurs" },

  // Système institutionnel et politique (47 questions)
  { q: "Qui nomme le Premier ministre ?", cat: "Système institutionnel" },
  { q: "Le Parlement est composé :", cat: "Système institutionnel" },
  { q: "Qu'est-ce que le pouvoir exécutif ? Le pouvoir :", cat: "Système institutionnel" },
  { q: "Les dirigeants sont élus par les citoyens dans :", cat: "Système institutionnel" },
  { q: "A-t-on le droit de ne pas respecter une loi ?", cat: "Système institutionnel" },
  { q: "Qui doit respecter la loi ?", cat: "Système institutionnel" },
  { q: "Quel est le rôle de l'autorité judiciaire ?", cat: "Système institutionnel" },
  { q: "Quel pouvoir détient un juge ? Le pouvoir :", cat: "Système institutionnel" },
  { q: "L'autorité judiciaire est exercée par :", cat: "Système institutionnel" },
  { q: "Que se passe-t-il si un ministre ne respecte pas la loi ?", cat: "Système institutionnel" },
  { q: "Qui est élu lors des élections législatives ?", cat: "Système institutionnel" },
  { q: "Combien de députés composent l'Assemblée nationale ?", cat: "Système institutionnel" },
  { q: "Quand sont élus les sénateurs ?", cat: "Système institutionnel" },
  { q: "Qui est élu lors des élections municipales ?", cat: "Système institutionnel" },
  { q: "Qui est élu lors des élections présidentielles ?", cat: "Système institutionnel" },
  { q: "À partir de quel âge a-t-on le droit de voter ?", cat: "Système institutionnel" },
  { q: "Pour combien de temps est élu le président de la République française ?", cat: "Système institutionnel" },
  { q: "Pour combien de temps sont élus les députés ?", cat: "Système institutionnel" },
  { q: "Pour combien de temps sont élus les sénateurs ?", cat: "Système institutionnel" },
  { q: "Qui possède le pouvoir exécutif ?", cat: "Système institutionnel" },
  { q: "Quelle condition est nécessaire pour voter aux élections ?", cat: "Système institutionnel" },
  { q: "Qui peut voter aux élections en France ?", cat: "Système institutionnel" },
  { q: "Que signifie « suffrage universel » ?", cat: "Système institutionnel" },
  { q: "Concernant les partis politiques, quelle proposition est correcte ?", cat: "Système institutionnel" },
  { q: "Quel est le rôle des députés ?", cat: "Système institutionnel" },
  { q: "La séparation des pouvoirs est un principe fondamental. Quels sont les trois pouvoirs concernés ?", cat: "Système institutionnel" },
  { q: "Qui possède le pouvoir législatif ?", cat: "Système institutionnel" },
  { q: "Qui sanctionne l'auteur d'un vol ?", cat: "Système institutionnel" },
  { q: "Qui élit les députés ?", cat: "Système institutionnel" },
  { q: "Qui vote les lois ?", cat: "Système institutionnel" },
  { q: "Qui réside au palais de l'Élysée ?", cat: "Système institutionnel" },
  { q: "Combien y a-t-il de départements en France ?", cat: "Système institutionnel" },
  { q: "Qui représente l'État dans un département ?", cat: "Système institutionnel" },
  { q: "Qui dirige la commune ?", cat: "Système institutionnel" },
  { q: "Est-ce que le président de la République a tous les pouvoirs ?", cat: "Système institutionnel" },
  { q: "Qui est le préfet ?", cat: "Système institutionnel" },
  { q: "Quel est le rôle du Parlement ?", cat: "Système institutionnel" },
  { q: "Quel est le régime politique de la France aujourd'hui ?", cat: "Système institutionnel" },
  { q: "Combien d'États font partie de l'Union européenne au 1er janvier 2025 ?", cat: "Système institutionnel" },
  { q: "Quel État n'est pas membre de l'Union européenne ?", cat: "Système institutionnel" },
  { q: "Quelle condition est nécessaire pour voter aux élections européennes ?", cat: "Système institutionnel" },
  { q: "À quelle fréquence les élections européennes sont-elles organisées ?", cat: "Système institutionnel" },
  { q: "Quel pays est un pays fondateur de l'Union européenne ?", cat: "Système institutionnel" },
  { q: "Quelle est la monnaie utilisée en France ?", cat: "Système institutionnel" },
  { q: "Qui élit les députés européens ?", cat: "Système institutionnel" },
  { q: "Quand célèbre-t-on la journée de l'Europe ?", cat: "Système institutionnel" },

  // Droits et devoirs (30 questions)
  { q: "Comment s'appelle la Constitution actuelle de la France ?", cat: "Droits et devoirs" },
  { q: "Comment s'appelle le texte qui énonce les droits et devoirs des personnes résidant en France ?", cat: "Droits et devoirs" },
  { q: "Concernant les droits individuels, quelle proposition est correcte ?", cat: "Droits et devoirs" },
  { q: "De quelle année date la Déclaration des droits de l'homme et du citoyen ?", cat: "Droits et devoirs" },
  { q: "Lequel de ces droits est un droit fondamental ?", cat: "Droits et devoirs" },
  { q: "Parmi ces textes, lequel garantit les droits et libertés en France ?", cat: "Droits et devoirs" },
  { q: "Qu'est-ce que la liberté d'expression ?", cat: "Droits et devoirs" },
  { q: "Quel droit permet à une personne de se défendre devant la justice ?", cat: "Droits et devoirs" },
  { q: "Quel est le texte fondateur établissant en France les droits et les devoirs de chaque citoyen ?", cat: "Droits et devoirs" },
  { q: "Quel texte a été adopté pendant la Révolution française ?", cat: "Droits et devoirs" },
  { q: "Quelle liberté permet à une personne de ne pas avoir de religion ?", cat: "Droits et devoirs" },
  { q: "Une femme peut avorter :", cat: "Droits et devoirs" },
  { q: "Est-il toujours possible de divorcer ?", cat: "Droits et devoirs" },
  { q: "La peine de mort est :", cat: "Droits et devoirs" },
  { q: "Concernant les limites aux libertés individuelles, quelle proposition est correcte ?", cat: "Droits et devoirs" },
  { q: "En France, est-ce légal d'être marié à plusieurs personnes en même temps ?", cat: "Droits et devoirs" },
  { q: "Faut-il réduire ses déchets ?", cat: "Droits et devoirs" },
  { q: "Jeter une bouteille dans la rue est :", cat: "Droits et devoirs" },
  { q: "Pourquoi les libertés individuelles peuvent-elles être limitées ?", cat: "Droits et devoirs" },
  { q: "Que doit faire une personne en cas d'accident ?", cat: "Droits et devoirs" },
  { q: "Que permet la citoyenneté française ?", cat: "Droits et devoirs" },
  { q: "Que risque une personne qui ne respecte pas la loi ?", cat: "Droits et devoirs" },
  { q: "Quel est le rôle de la gendarmerie ?", cat: "Droits et devoirs" },
  { q: "Quel est le rôle de la police ?", cat: "Droits et devoirs" },
  { q: "Qu'est-ce qu'une infraction ?", cat: "Droits et devoirs" },
  { q: "Comment peut-on réduire ses déchets ?", cat: "Droits et devoirs" },
  { q: "Déposer une machine à laver cassée sur le trottoir est :", cat: "Droits et devoirs" },
  { q: "En quoi consiste la traite des êtres humains ?", cat: "Droits et devoirs" },
  { q: "Que doit faire une victime de violences ?", cat: "Droits et devoirs" },
  { q: "Quelle est l'infraction la plus grave ?", cat: "Droits et devoirs" },

  // Histoire géographie et culture (35 questions) - NOTE: Listed as 35 but actual count may vary
  { q: "En quelle année a débuté la Révolution française ?", cat: "Histoire et culture" },
  { q: "Qui était Napoléon Ier ?", cat: "Histoire et culture" },
  { q: "Lequel de ces personnages historiques est français ?", cat: "Histoire et culture" },
  { q: "Dans quelle République est-on aujourd'hui ?", cat: "Histoire et culture" },
  { q: "Qu'est-ce que la Shoah ?", cat: "Histoire et culture" },
  { q: "Quel pays ou région du monde a été colonisé par la France ?", cat: "Histoire et culture" },
  { q: "Qui a rendu l'école gratuite, laïque et obligatoire ?", cat: "Histoire et culture" },
  { q: "Quand a eu lieu la Seconde Guerre mondiale ?", cat: "Histoire et culture" },
  { q: "Quand a eu lieu la Première Guerre mondiale ?", cat: "Histoire et culture" },
  { q: "En quelle année a été créée la Communauté Économique Européenne (CEE) ?", cat: "Histoire et culture" },
  { q: "Le 11 novembre est un jour férié. À quoi correspond cette date ?", cat: "Histoire et culture" },
  { q: "Qui a été le premier Président élu sous la Ve République ?", cat: "Histoire et culture" },
  { q: "En quelle année l'esclavage a-t-il été aboli définitivement en France ?", cat: "Histoire et culture" },
  { q: "Depuis quelle année l'école publique est-elle gratuite ?", cat: "Histoire et culture" },
  { q: "Combien y a-t-il eu de républiques en France ?", cat: "Histoire et culture" },
  { q: "Qui était le roi de France au moment de la Révolution française ?", cat: "Histoire et culture" },
  { q: "Qui a fondé la Ve République ?", cat: "Histoire et culture" },
  { q: "Que célèbre-t-on le 14 juillet ?", cat: "Histoire et culture" },
  { q: "Quelle guerre a eu lieu entre 1914 et 1918 ?", cat: "Histoire et culture" },
  { q: "Pourquoi l'année 1958 est importante pour la France ?", cat: "Histoire et culture" },
  { q: "Quel fleuve coule en France ?", cat: "Histoire et culture" },
  { q: "Quelle ville est française ?", cat: "Histoire et culture" },
  { q: "Quel océan borde la côte ouest française ?", cat: "Histoire et culture" },
  { q: "Qu'est-ce que Paris ?", cat: "Histoire et culture" },
  { q: "Quelle est la capitale de la France ?", cat: "Histoire et culture" },
  { q: "Sur quel continent se situe la France métropolitaine ?", cat: "Histoire et culture" },
  { q: "Quelle île est un département d'outre-mer français ?", cat: "Histoire et culture" },
  { q: "Combien y a-t-il de régions en France métropolitaine ?", cat: "Histoire et culture" },
  { q: "Quelle ville est un grand port maritime ?", cat: "Histoire et culture" },
  { q: "Quelle est la mer au sud de la France métropolitaine ?", cat: "Histoire et culture" },
  { q: "Quelle ville est située au bord de la mer Méditerranée ?", cat: "Histoire et culture" },
  { q: "Où se situe la Corse ?", cat: "Histoire et culture" },
  { q: "Quelle chaîne de montagnes est située entre la France et l'Italie ?", cat: "Histoire et culture" },
  { q: "Qui était Molière ?", cat: "Histoire et culture" },
  { q: "Qui était Charles Baudelaire ?", cat: "Histoire et culture" },
  { q: "Qui était George Sand ?", cat: "Histoire et culture" },
  { q: "Qui était Simone de Beauvoir ?", cat: "Histoire et culture" },
  { q: "Qui était Albert Camus ?", cat: "Histoire et culture" },
  { q: "Qui était Paul Cézanne ?", cat: "Histoire et culture" },
  { q: "Qui était Marc Chagall ?", cat: "Histoire et culture" },
  { q: "Qui était Joséphine Baker ?", cat: "Histoire et culture" },
  { q: "Qui était une chanteuse française célèbre ?", cat: "Histoire et culture" },
  { q: "Qu'est-ce que le Louvre ?", cat: "Histoire et culture" },
  { q: "Qui était Jean de la Fontaine ?", cat: "Histoire et culture" },
  { q: "Quel écrivain est français ?", cat: "Histoire et culture" },
  { q: "Dans quelle ville se trouve la tour Eiffel ?", cat: "Histoire et culture" },
  { q: "Quand célèbre-t-on Noël ?", cat: "Histoire et culture" },

  // Vivre dans la société française (31 questions)
  { q: "Quel numéro d'urgence permet d'appeler le SAMU ?", cat: "Vivre dans la société française" },
  { q: "Quel numéro d'urgence permet d'appeler les pompiers ?", cat: "Vivre dans la société française" },
  { q: "Après avoir obtenu le permis de conduire, que faut-il faire pour pouvoir conduire sa voiture ?", cat: "Vivre dans la société française" },
  { q: "À quelles conditions un mariage est-il reconnu juridiquement ?", cat: "Vivre dans la société française" },
  { q: "Quand faut-il déclarer son enfant au service d'état civil de la mairie ?", cat: "Vivre dans la société française" },
  { q: "Le travail non déclaré est :", cat: "Vivre dans la société française" },
  { q: "Que doit faire un employeur pour fixer un salaire ?", cat: "Vivre dans la société française" },
  { q: "Qu'est-ce que le SMIC ?", cat: "Vivre dans la société française" },
  { q: "Quelle est la première démarche à réaliser pour chercher un emploi ?", cat: "Vivre dans la société française" },
  { q: "Quelle est la durée légale du temps de travail par semaine ?", cat: "Vivre dans la société française" },
  { q: "Qui est aidé par France Travail ?", cat: "Vivre dans la société française" },
  { q: "Une personne étrangère en situation régulière peut créer son entreprise :", cat: "Vivre dans la société française" },
  { q: "Une femme peut-elle créer son entreprise ?", cat: "Vivre dans la société française" },
  { q: "À partir de quel âge un mineur peut-il travailler ?", cat: "Vivre dans la société française" },
  { q: "Auprès de quel organisme faut-il demander le remboursement des frais de santé ?", cat: "Vivre dans la société française" },
  { q: "Qu'est-ce qu'un numéro d'urgence ?", cat: "Vivre dans la société française" },
  { q: "Concernant l'accès aux soins, quelle proposition est correcte ?", cat: "Vivre dans la société française" },
  { q: "En cas de problème de santé non urgent, à qui faut-il s'adresser en premier ?", cat: "Vivre dans la société française" },
  { q: "Quel est le rôle du médecin traitant ?", cat: "Vivre dans la société française" },
  { q: "Dans quelles situations doit-on se rendre aux urgences de l'hôpital ?", cat: "Vivre dans la société française" },
  { q: "Quel est l'objectif des vaccinations obligatoires ?", cat: "Vivre dans la société française" },
  { q: "À quoi sert la carte Vitale ?", cat: "Vivre dans la société française" },
  { q: "À quoi sert une mutuelle santé ?", cat: "Vivre dans la société française" },
  { q: "Jusqu'à quel âge l'école est-elle obligatoire ?", cat: "Vivre dans la société française" },
  { q: "L'autorité parentale prévoit l'obligation :", cat: "Vivre dans la société française" },
  { q: "Pour qui l'école est-elle obligatoire ?", cat: "Vivre dans la société française" },
  { q: "Quel diplôme obtient-on à la fin du lycée ?", cat: "Vivre dans la société française" },
  { q: "Dans quels établissements scolaires vont les élèves après l'école élémentaire ?", cat: "Vivre dans la société française" },
  { q: "Un enfant inscrit à l'école :", cat: "Vivre dans la société française" },
  { q: "Les enfants qui ne parlent pas français :", cat: "Vivre dans la société française" }
];

export const crQuestions = [
  // Principes et valeurs de la République (40 questions)
  { q: "Parmi les propositions suivantes, laquelle constitue une participation citoyenne ?", cat: "Principes et valeurs" },
  { q: "Que garantit la liberté d'expression ?", cat: "Principes et valeurs" },
  { q: "À quoi sert un titre de séjour ?", cat: "Principes et valeurs" },
  { q: "La liberté de circulation permet à toute personne de :", cat: "Principes et valeurs" },
  { q: "Sur quel site internet peut-on retrouver le symbole de la République française ?", cat: "Principes et valeurs" },
  { q: "Complétez ces paroles de la Marseillaise : \"Aux armes […] ! Formez vos bataillons\"", cat: "Principes et valeurs" },
  { q: "Complétez les paroles de la Marseillaise : \"Allons enfants de la patrie […]\"", cat: "Principes et valeurs" },
  { q: "En application de la liberté individuelle, quelle proposition est correcte ? Une personne peut :", cat: "Principes et valeurs" },
  { q: "Concernant la pratique de la religion, quelle proposition est correcte ?", cat: "Principes et valeurs" },
  { q: "En tant que parent, peut-on refuser que son enfant participe aux cours de sport à l'école car ils sont mixtes ?", cat: "Principes et valeurs" },
  { q: "Quelle est la devise de la France ?", cat: "Principes et valeurs" },
  { q: "La répudiation de sa femme est :", cat: "Principes et valeurs" },
  { q: "Les impôts permettent de financer les dépenses publiques. Quelle proposition est correcte ?", cat: "Principes et valeurs" },
  { q: "Peut-on brûler publiquement un drapeau français ?", cat: "Principes et valeurs" },
  { q: "Que fait l'État pour lutter contre les discriminations ?", cat: "Principes et valeurs" },
  { q: "Que représente Marianne ?", cat: "Principes et valeurs" },
  { q: "Qu'est-ce que la liberté d'association ?", cat: "Principes et valeurs" },
  { q: "Qu'est-ce que la liberté ?", cat: "Principes et valeurs" },
  { q: "Qu'est-ce que la Marseillaise ?", cat: "Principes et valeurs" },
  { q: "Sur quel document peut-on voir Marianne ?", cat: "Principes et valeurs" },
  { q: "Un employeur refuse d'embaucher des femmes dans son entreprise. Que dit la loi ?", cat: "Principes et valeurs" },
  { q: "Une des valeurs de la devise républicaine est l'égalité. Qu'est-ce que cela signifie ?", cat: "Principes et valeurs" },
  { q: "Quelle est la place de la langue française dans la République ?", cat: "Principes et valeurs" },
  { q: "Quels sont des symboles officiels de la République française ?", cat: "Principes et valeurs" },
  { q: "A-t-on le droit d'insulter publiquement quelqu'un parce qu'il est différent (handicap, apparence physique, sexe…) ?", cat: "Principes et valeurs" },
  { q: "Le régime de la France est :", cat: "Principes et valeurs" },
  { q: "Pourquoi le principe de laïcité doit-il être respecté à l'école ?", cat: "Principes et valeurs" },
  { q: "En quelle année la loi de séparation des Églises et de l'Etat a-t-elle été votée ?", cat: "Principes et valeurs" },
  { q: "Une personne a-t-elle le droit de ne pas croire en une religion ?", cat: "Principes et valeurs" },
  { q: "Quel droit est garanti par la laïcité ?", cat: "Principes et valeurs" },
  { q: "À l'école publique, qui peut porter des signes religieux très visibles ?", cat: "Principes et valeurs" },
  { q: "Selon le principe de laïcité, que signifie la neutralité de l'État ?", cat: "Principes et valeurs" },
  { q: "Que peut faire un usager du service public dans une mairie ?", cat: "Principes et valeurs" },
  { q: "Qui doit respecter le principe de neutralité religieuse dans une préfecture ?", cat: "Principes et valeurs" },
  { q: "La laïcité impose-t-elle aux agents publics d'être neutres vis-à-vis des usagers ?", cat: "Principes et valeurs" },
  { q: "Que garantit le principe de laïcité ?", cat: "Principes et valeurs" },
  { q: "A-t-on le droit de changer de religion ?", cat: "Principes et valeurs" },
  { q: "Que représente la laïcité ?", cat: "Principes et valeurs" },
  { q: "Qu'est ce qui est interdit par la Charte de la laïcité à l'école ?", cat: "Principes et valeurs" },
  { q: "Que dit l'article 1er de la Constitution française ?", cat: "Principes et valeurs" },

  // Système institutionnel et politique (50 questions)
  { q: "Qu'est-ce que l'État de droit ?", cat: "Système institutionnel" },
  { q: "Le président de la République a commis un crime. Quelle proposition est correcte ?", cat: "Système institutionnel" },
  { q: "La loi est l'expression de :", cat: "Système institutionnel" },
  { q: "Quelle est la durée du mandat du conseil municipal et du maire ?", cat: "Système institutionnel" },
  { q: "Que garantit l'État de droit ?", cat: "Système institutionnel" },
  { q: "Une personne peut-elle voter à la place d'une autre ?", cat: "Système institutionnel" },
  { q: "Est-ce que le vote est obligatoire ?", cat: "Système institutionnel" },
  { q: "À la fin de son mandat, le président de la République peut-il décider de rester au pouvoir ?", cat: "Système institutionnel" },
  { q: "Qui dirige l'action du Gouvernement ?", cat: "Système institutionnel" },
  { q: "Qui nomme le Premier ministre ?", cat: "Système institutionnel" },
  { q: "Quelle est l'organisation administrative de la France ?", cat: "Système institutionnel" },
  { q: "Qu'est-ce que le pouvoir législatif ? Le pouvoir :", cat: "Système institutionnel" },
  { q: "Pourquoi séparer les trois pouvoirs dans une démocratie ?", cat: "Système institutionnel" },
  { q: "Qui sanctionne l'auteur d'un vol ?", cat: "Système institutionnel" },
  { q: "Quel est le rôle du gouvernement ?", cat: "Système institutionnel" },
  { q: "Que se passe-t-il si un ministre ne respecte pas la loi ?", cat: "Système institutionnel" },
  { q: "Combien de députés composent l'Assemblée nationale ?", cat: "Système institutionnel" },
  { q: "Qui peut voter aux élections en France ?", cat: "Système institutionnel" },
  { q: "Pour combien de temps sont élus les sénateurs ?", cat: "Système institutionnel" },
  { q: "La séparation des pouvoirs est un principe fondamental. Quels sont les trois pouvoirs concernés ?", cat: "Système institutionnel" },
  { q: "Est-ce que le président de la République a tous les pouvoirs ?", cat: "Système institutionnel" },
  { q: "Qui est le préfet ?", cat: "Système institutionnel" },
  { q: "Quelle condition est nécessaire pour voter aux élections ?", cat: "Système institutionnel" },
  { q: "Qui dirige la commune ?", cat: "Système institutionnel" },
  { q: "Quel est le régime politique de la France aujourd'hui ?", cat: "Système institutionnel" },
  { q: "Qu'est-ce que l'Hôtel de Matignon ?", cat: "Système institutionnel" },
  { q: "Le Parlement est composé :", cat: "Système institutionnel" },
  { q: "Quel est le rôle du président de la République ?", cat: "Système institutionnel" },
  { q: "Quel est le rôle du Premier ministre ?", cat: "Système institutionnel" },
  { q: "Qui est le chef du Gouvernement ?", cat: "Système institutionnel" },
  { q: "Combien y a-t-il de régions en France ?", cat: "Système institutionnel" },
  { q: "Quel est le rôle du Défenseur des droits ?", cat: "Système institutionnel" },
  { q: "Depuis quand l'euro est-elle la monnaie unique ?", cat: "Système institutionnel" },
  { q: "Quel est le rôle principal du département ?", cat: "Système institutionnel" },
  { q: "Quel est le rôle principal des communes ?", cat: "Système institutionnel" },
  { q: "Combien de communes environ existe-t-il en France ?", cat: "Système institutionnel" },
  { q: "Quel traité concerne la construction de l'Union européenne ?", cat: "Système institutionnel" },
  { q: "Quel État a quitté l'Union européenne en 2020 ?", cat: "Système institutionnel" },
  { q: "Quelle est la devise de l'Union européenne ?", cat: "Système institutionnel" },
  { q: "Quel est l'hymne de l'Union européenne ?", cat: "Système institutionnel" },
  { q: "De quoi est composé le drapeau européen ?", cat: "Système institutionnel" },
  { q: "De quelle couleur est le drapeau européen ?", cat: "Système institutionnel" },
  { q: "En quelle année le traité de Maastricht, qui marque la fondation de l'Union européenne, a-t-il été signé ?", cat: "Système institutionnel" },
  { q: "Où est le siège du Parlement européen ?", cat: "Système institutionnel" },
  { q: "Où est le siège de la Commission européenne ?", cat: "Système institutionnel" },
  { q: "Quel État n'est pas membre de l'Union européenne ?", cat: "Système institutionnel" },
  { q: "Quand célèbre-t-on la journée de l'Europe ?", cat: "Système institutionnel" },
  { q: "À quelle fréquence les élections européennes sont-elles organisées ?", cat: "Système institutionnel" },
  { q: "Quelle condition est nécessaire pour voter aux élections européennes ?", cat: "Système institutionnel" },
  { q: "Quel pays est un pays fondateur de l'Union européenne ?", cat: "Système institutionnel" },

  // Droits et devoirs (38 questions)
  { q: "À quelle liberté la PMA fait-elle référence ?", cat: "Droits et devoirs" },
  { q: "Au nom de quoi l'État justifie-t-il la restriction des droits ?", cat: "Droits et devoirs" },
  { q: "Concernant le droit de se marier, quelle proposition est correcte ?", cat: "Droits et devoirs" },
  { q: "Est-il toujours possible de divorcer ?", cat: "Droits et devoirs" },
  { q: "La peine de mort est :", cat: "Droits et devoirs" },
  { q: "Laquelle de ces citations est inscrite dans la Déclaration des Droits de l'homme et du Citoyen de 1789 ?", cat: "Droits et devoirs" },
  { q: "Le recours à l'avortement est-il autorisé ?", cat: "Droits et devoirs" },
  { q: "Que contient la Constitution ?", cat: "Droits et devoirs" },
  { q: "Que garantit la liberté de la presse ?", cat: "Droits et devoirs" },
  { q: "Que prévoit la Charte de l'environnement ?", cat: "Droits et devoirs" },
  { q: "Que signifie la dignité humaine ?", cat: "Droits et devoirs" },
  { q: "Que signifie le droit de manifester ?", cat: "Droits et devoirs" },
  { q: "Que signifie PMA ?", cat: "Droits et devoirs" },
  { q: "Quel texte est le plus difficile à modifier ?", cat: "Droits et devoirs" },
  { q: "Quelle liberté permet à une personne de croire en la religion de son choix ?", cat: "Droits et devoirs" },
  { q: "Qu'est-ce que le droit de grève ?", cat: "Droits et devoirs" },
  { q: "Qu'est-ce que la Constitution ?", cat: "Droits et devoirs" },
  { q: "Qui peut demander à avorter ?", cat: "Droits et devoirs" },
  { q: "Une femme majeure de nationalité française a-t-elle le droit de voter aux élections ?", cat: "Droits et devoirs" },
  { q: "Concernant l'utilisation des réseaux sociaux, quelle proposition est correcte ?", cat: "Droits et devoirs" },
  { q: "Jeter un mégot par terre est :", cat: "Droits et devoirs" },
  { q: "L'État peut-il limiter les droits et libertés ?", cat: "Droits et devoirs" },
  { q: "Parmi ces actions, laquelle permet d'adopter une attitude respectueuse de l'environnement ?", cat: "Droits et devoirs" },
  { q: "Quelle proposition constitue une obligation ?", cat: "Droits et devoirs" },
  { q: "Pour quel motif peut-on limiter la liberté d'expression ?", cat: "Droits et devoirs" },
  { q: "Pourquoi doit-on trier ses déchets ?", cat: "Droits et devoirs" },
  { q: "Que doit faire une victime de violences ?", cat: "Droits et devoirs" },
  { q: "Que doit-on faire face aux ordres des policiers ou gendarmes ?", cat: "Droits et devoirs" },
  { q: "Quel est le rôle de la police ?", cat: "Droits et devoirs" },
  { q: "Quel est un exemple d'assistance à personne en danger ?", cat: "Droits et devoirs" },
  { q: "Quel exemple illustre une limitation de liberté pour protéger l'intérêt général ?", cat: "Droits et devoirs" },
  { q: "Quelle est l'attitude à avoir lorsque qu'on est témoin de violences ?", cat: "Droits et devoirs" },
  { q: "Quelle est l'infraction la plus grave ?", cat: "Droits et devoirs" },
  { q: "Quelle obligation concerne toutes les personnes résidant en France quelle que soit leur nationalité ?", cat: "Droits et devoirs" },
  { q: "Quelle proposition représente un exemple de crime ?", cat: "Droits et devoirs" },
  { q: "Quelle proposition représente un exemple de délit ?", cat: "Droits et devoirs" },
  { q: "Qui veille au maintien de l'ordre public ?", cat: "Droits et devoirs" },
  { q: "S'agissant des déchets, quelle proposition est correcte ?", cat: "Droits et devoirs" },

  // Histoire géographie et culture (52 questions)
  { q: "Quel était le surnom de Louis XIV ?", cat: "Histoire et culture" },
  { q: "Quel roi de France a été exécuté pendant la Révolution française ?", cat: "Histoire et culture" },
  { q: "En quelle année Napoléon Ier est-il devenu empereur ?", cat: "Histoire et culture" },
  { q: "Lequel de ces personnages a un lien avec la République française ?", cat: "Histoire et culture" },
  { q: "De quand date l'appel à la résistance du général de Gaulle ?", cat: "Histoire et culture" },
  { q: "Pourquoi la Shoah est-elle étudiée à l'école ?", cat: "Histoire et culture" },
  { q: "Quel pays a été colonisé par la France ?", cat: "Histoire et culture" },
  { q: "Depuis quand les Français élisent-ils le président de la République au suffrage universel direct ?", cat: "Histoire et culture" },
  { q: "Quelle est la première étape de la construction européenne en 1951 ?", cat: "Histoire et culture" },
  { q: "Durant le mandat de quel président la peine de mort a-t-elle été abolie ?", cat: "Histoire et culture" },
  { q: "Quel régime politique a été mis en place pendant la Révolution française en 1792 ?", cat: "Histoire et culture" },
  { q: "Qui était une figure de la Résistance française pendant la Seconde Guerre mondiale ?", cat: "Histoire et culture" },
  { q: "En 1944, qu'est-ce qui a changé pour les femmes ?", cat: "Histoire et culture" },
  { q: "Quelle organisation internationale a été créée en 1945 après la Seconde Guerre mondiale ?", cat: "Histoire et culture" },
  { q: "Quelle peine a été supprimée en 1981 ?", cat: "Histoire et culture" },
  { q: "En quelle année l'euro est-elle devenue la monnaie utilisée en France ?", cat: "Histoire et culture" },
  { q: "En quelle année a commencé la Première Guerre mondiale ?", cat: "Histoire et culture" },
  { q: "Où a eu lieu le débarquement en 1944 ?", cat: "Histoire et culture" },
  { q: "Quel continent a été le plus concerné par la décolonisation française après la Seconde Guerre mondiale ?", cat: "Histoire et culture" },
  { q: "Que fête-t-on le 8 mai ?", cat: "Histoire et culture" },
  { q: "Quelle mer ou océan borde la France métropolitaine ?", cat: "Histoire et culture" },
  { q: "Quel pays a une frontière terrestre avec la France métropolitaine ?", cat: "Histoire et culture" },
  { q: "Quelle ville française est un port maritime ?", cat: "Histoire et culture" },
  { q: "Quelle mer se situe entre la France et l'Angleterre ?", cat: "Histoire et culture" },
  { q: "Qu'est ce que la France d'outre-mer ?", cat: "Histoire et culture" },
  { q: "Quelle chaîne de montagnes est située entre la France et l'Espagne ?", cat: "Histoire et culture" },
  { q: "Quelle île française se trouve dans l'océan Indien ?", cat: "Histoire et culture" },
  { q: "Quelle est la population approximative de la France en 2025 ?", cat: "Histoire et culture" },
  { q: "Quel fleuve traverse Paris ?", cat: "Histoire et culture" },
  { q: "Lequel de ces pays partage des frontières terrestres avec la France ?", cat: "Histoire et culture" },
  { q: "Quel pays a une frontière avec la France métropolitaine au nord-est ?", cat: "Histoire et culture" },
  { q: "Où se trouvent les principales activités économiques en France ?", cat: "Histoire et culture" },
  { q: "Parmi ces pays, lequel attire le plus de visiteurs chaque année ?", cat: "Histoire et culture" },
  { q: "Où habite la majorité des Français ?", cat: "Histoire et culture" },
  { q: "Quelle région est la plus peuplée ?", cat: "Histoire et culture" },
  { q: "Quelle ville française fait partie des 10 plus grandes métropoles du pays ?", cat: "Histoire et culture" },
  { q: "Lequel de ces départements de France est le plus touristique ?", cat: "Histoire et culture" },
  { q: "Quand peut-on visiter gratuitement des lieux culturels en France ?", cat: "Histoire et culture" },
  { q: "Combien de personnes parlent français dans le monde ?", cat: "Histoire et culture" },
  { q: "Qui était Marguerite Yourcenar ?", cat: "Histoire et culture" },
  { q: "Quel peintre est français ?", cat: "Histoire et culture" },
  { q: "Quel musée est situé à Paris ?", cat: "Histoire et culture" },
  { q: "Qui était Auguste Rodin ?", cat: "Histoire et culture" },
  { q: "Quel est le classement de la langue française parmi les langues les plus parlées dans le monde ?", cat: "Histoire et culture" },
  { q: "Quelle cathédrale célèbre a été en partie détruite par un incendie en 2019 ?", cat: "Histoire et culture" },
  { q: "Qui était une écrivaine française célèbre ?", cat: "Histoire et culture" },
  { q: "Qui était un célèbre musicien français ?", cat: "Histoire et culture" },
  { q: "Qui était Auguste Renoir ?", cat: "Histoire et culture" },
  { q: "Quelle fête est française ?", cat: "Histoire et culture" },

  // Vivre dans la société française (31 questions, some overlap with CSP)
  { q: "Quel mariage est reconnu par l'État ?", cat: "Vivre dans la société française" },
  { q: "Auprès de quelle institution les parents peuvent-ils inscrire leur enfant à l'école publique ?", cat: "Vivre dans la société française" },
  { q: "En cas de divorce, qui exerce l'autorité parentale ?", cat: "Vivre dans la société française" },
  { q: "Quelle aide permet aux personnes qui ont des difficultés financières d'avoir un avocat ?", cat: "Vivre dans la société française" },
  { q: "Où faut-il déclarer la naissance d'un enfant ?", cat: "Vivre dans la société française" },
  { q: "Quelle est l'une des conditions pour passer l'examen du permis de conduire ?", cat: "Vivre dans la société française" },
  { q: "Un bail locatif est valide s'il est :", cat: "Vivre dans la société française" },
  { q: "Où peut-on déposer un lave-vaisselle cassé ?", cat: "Vivre dans la société française" },
  { q: "Quel numéro d'urgence permet d'appeler la police ?", cat: "Vivre dans la société française" },
  { q: "Concernant l'accès aux soins, quelle proposition est correcte ?", cat: "Vivre dans la société française" },
  { q: "À qui est accessible la contraception ?", cat: "Vivre dans la société française" },
  { q: "Qu'est-ce que le principe de confidentialité dans le domaine de la santé ?", cat: "Vivre dans la société française" },
  { q: "L'inscription à l'Assurance maladie est :", cat: "Vivre dans la société française" },
  { q: "Qui peut demander un congé parental d'éducation ?", cat: "Vivre dans la société française" },
  { q: "Quelles sont les affaires traitées par le conseil de prud'hommes ?", cat: "Vivre dans la société française" },
  { q: "Travailler sans être déclaré est :", cat: "Vivre dans la société française" },
  { q: "Lorsqu'un employeur veut qu'un salarié travaille plus longtemps que la durée prévue dans le contrat de travail :", cat: "Vivre dans la société française" },
  { q: "Quelle est la mission de France Travail ?", cat: "Vivre dans la société française" },
  { q: "Dans une entreprise, le droit syndical permet :", cat: "Vivre dans la société française" },
  { q: "Dans une entreprise, le droit de grève autorise :", cat: "Vivre dans la société française" },
  { q: "Quelles sont les conditions pour toucher les allocations chômage ?", cat: "Vivre dans la société française" },
  { q: "Qu'est-ce que l'école maternelle ?", cat: "Vivre dans la société française" },
  { q: "Comment s'appelle le diplôme passé par les élèves à la fin du collège ?", cat: "Vivre dans la société française" },
  { q: "Les parents d'élève ont le droit de :", cat: "Vivre dans la société française" },
  { q: "Qui peut manger à la cantine scolaire ?", cat: "Vivre dans la société française" },
  { q: "À quel âge commence l'instruction obligatoire des enfants ?", cat: "Vivre dans la société française" },
  { q: "Quel est l'âge de la majorité ?", cat: "Vivre dans la société française" },
  { q: "À l'école, il est interdit aux parents de :", cat: "Vivre dans la société française" },
  { q: "Quel motif d'absence est accepté par l'école ?", cat: "Vivre dans la société française" },
  { q: "Des parents ne respectent pas l'obligation d'instruction pour leurs enfants. Quelle sanction maximale risquent-ils ?", cat: "Vivre dans la société française" },
  { q: "Quand ont lieu les vacances scolaires de Noël ?", cat: "Vivre dans la société française" },
  { q: "À l'école, un enfant en situation de handicap :", cat: "Vivre dans la société française" }
];
